[build]
command = "npm run build"
publish = "dist/client-job-portal/browser"

[[plugins]]
package = "@netlify/plugin-replace"

  [plugins.inputs]
  files = ["dist/client-job-portal/browser/config.json"]
  from = "__API_URL__"
  to = "$API_URL"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
